[package]
name = "decompdb-cli"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"

[dependencies]
cu = { workspace = true, features = [
    "cli", "process", "toml", "json", "derive", "coroutine-heavy"
] }
tyyaml = { path = "../tyyaml" }
elf = "0.8.0"
fxhash.workspace = true
gimli = "0.32.1"
rayon = "1.11.0"
regex = "1.11.1"
serde.workspace = true
spin = "0.10.0"
tokio = "1"
shell-words = "1.1.0"
clang-ast = "0.1.33"
dashmap = { version = "6.1.0", features = ["serde"] }
depfile = "0.1.1"

[[bin]]
name = "decompdb"
path = "src/main.rs"
