[paths]
elf = "../../../botw-decomp/build/uking"
extract = "../../../botw-decomp/build/decompdb-extract"

[paths.functions-csv]
path = "../../../botw-decomp/data/uking_functions.csv"
base-address = 0x7100000000
address-column = 0
symbol-column = 3

[paths.data-csv]
path = "../../../botw-decomp/data/data_symbols.csv"
base-address = 0x7100000000
address-column = 0 
symbol-column = 1

[extract]
pointer-width = 64
ptmd-repr = ["u64", 1]
ptmf-repr = ["u64", 2]
vfptr-field-regex = "^_vptr\\$"

[extract.type-optimizer.pick-union-member]
"uking::ui::PouchItem::Data" = "cook"
"fpos_t" = "__opaque"

[extract.name-resolution]
rules = []
test = []

[extract.name-resolution.override]
# de-templatize
"^sead::OffsetList<.*>$" = "sead::OffsetList"
"^sead::DelegateEvent<.*>$" = "sead::DelegateEvent"

# [extract.type-optimizer.opaque-if]
# name-matches = [
#     "^std::__va_list$", 
# ]
# struct-member-name-contains = [
#     "__clang"
# ]

