version: '3'

tasks:
  test:
    cmds:
        # -Xclang -ast-dump=json
          # clang++
        # -xc++
      # -Xclang -emit-ast
        # -ast-dump
        # -fsyntax-only
      # /home/piston/dev/botw-decomp/toolchain/clang-4.0.1/bin/clang
      - cmd: >
          clang
          -Xclang -ast-dump=json
          -fsyntax-only
          -I/home/piston/dev/botw-decomp/toolchain/clang-4.0.1/include/c++/v1
          test.cpp
          --target=aarch64-linux-elf 
          --sysroot=/home/piston/dev/botw-decomp/toolchain/musl
          -DUKING_NX_V150 
          -O3 -g -std=c++1z   
          -I/home/piston/dev/botw-decomp/lib/sead/include 
          -I/home/piston/dev/botw-decomp/lib/NintendoSDK/include 
          -D SWITCH -D NNSDK -D MATCHING_HACK_NX_CLANG 
          -D SWITCH -D NNSDK -D MATCHING_HACK_NX_CLANG 
          -mcpu=cortex-a57+fp+simd+crypto+crc 
          -mno-implicit-float 
          -stdlib=libc++ 
          -fPIC 
          -fstandalone-debug 
          -fcolor-diagnostics 
          -Wno-unused-command-line-argument 
          -fdebug-prefix-map=/tmp=/home/piston/dev/botw-decomp/build 
          -fno-exceptions 
          -fno-strict-aliasing 
          -Wall 
          -Wextra 
          -Wdeprecated 
          -Wno-invalid-offsetof 
          | bun post.ts > out.json

        #
